### ISSUE TITLE
Update please on ContentDB

### ISSUE THREAD

**Issue by ghost** [mt-historical/columnia#1]
Hello,

I noticed that there was a Maintainer change, and saw the few changes here on Github, like dependancy (optional) and mod.conf, BUT on ContentDB it's still the outdated one.

Updating the Mod on ContentDB, please.

**Comment by Niklp09** [comment]
Updated the ContentDB settings, an update should be created in the next 24 hours.

**Comment by ghost** [comment]
Thanks.

Even if I'm not using Moreblocks and Columnia right now, the options to use Columnia together with Moreblocks, imagin what you can build with both mods.

**Comment by Niklp09** [comment]
Created a new release manually, auto-update should work now.

**Comment by ghost** [comment]
Thanks again.

Thanks for maintaining and updating this Mod, AND thanks to Glunggi for creating this Mod.
